### ISSUE TITLE
Compilation errors due to missing `description` for `Error` implementation

### ISSUE THREAD

**Issue by mboogerd** [KizzyCode/etrace#1]
I'm encountering the following error when trying to use [rust-libp2p](https://github.com/libp2p/rust-libp2p), and consecutively, also when trying to test/release this project. Given that this method is [soft-deprecated](https://doc.rust-lang.org/std/error/trait.Error.html), I'm guessing that there may be something wrong on my end, but I don't know what it would be.

Could you help me on my way?

Using versions
- cargo 1.26.0 (0e7c5a931 2018-04-06)
- rustc 1.26.2 (594fb253c 2018-06-01)

```rust
error[E0046]: not all trait items implemented, missing: `description`
  --> src/lib.rs:27:1
   |
27 | impl std::error::Error for WrappedError {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `description` in implementation
error[E0046]: not all trait items implemented, missing: `description`
  --> src/lib.rs:96:1
   |
96 | impl<T: std::fmt::Debug + Send> std::error::Error for Error<T> {}
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `description` in implementation
   |
   |
   = note: `description` from trait: `fn(&Self) -> &str`
   = note: `description` from trait: `fn(&Self) -> &str`


error[E0046]: not all trait items implemented, missing: `description`
  --> src/lib.rs:96:1
   |
96 | impl<T: std::fmt::Debug + Send> std::error::Error for Error<T> {}
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `description` in implementation
   |
   = note: `description` from trait: `fn(&Self) -> &str`
```

**Comment by KizzyCode** [comment]
Apparently there is no default implementation for `description` in [1.26.1](https://doc.rust-lang.org/1.26.1/std/error/trait.Error.html).

**Comment by mboogerd** [comment]
I figured it would be something like that, apologies for my noobieness! Shall I close the linked PR for you?

**Comment by KizzyCode** [comment]
Nope 😊; since there is no deprecation warning (yet) and some people still use old Rust versions (e.g. the preinstalled package in LTS distros) IMHO it won't hurt to implement this for the time being...

**Comment by KizzyCode** [comment]
Now it should work with 1.26; TY for your issue and pull request 😄

**Comment by mboogerd** [comment]
I was one of those guys using older Rust versions indeed... Thanks for your quick response, happy to help out :)
